"""Add brand category and sku to products

Revision ID: 0fa1e7725cf6
Revises: e5b5f5cec498
Create Date: 2026-07-01 12:15:37.100920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa1e7725cf6'
down_revision = 'e5b5f5cec498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sku')
        batch_op.drop_column('category')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
